spring:
  datasource:
    url: jdbc:mysql://localhost:3308/product_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true